# E201: Ignore whitespace after [ and (.
# E202: Ignore whitespace before ) and ].

[tool.ruff]
line-length = 100
exclude = ["venv", "__pycache__", ".git", "migrations", ".mypy_cache", ".pytest_cache", "node_modules"]

[tool.ruff.lint]
ignore = ["E201", "E202"]
select = ["E", "F"]  # enable pycodestyle (E) and pyflakes (F)
extend-select = ["E501"] # Explicitly turn on E501 (line too long)